#!/usr/bin/env node
import { cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { appendAudit, distRoot, exists, listFiles, readConfig, rootDir, runCommand, sha256File, toPosix, writeJson } from "./harness-core.mjs";

const defaultOutputRoot = path.join(distRoot, "starter-template");
const defaultReportPath = path.join(rootDir, "reports", "template-package-manifest.json");

const defaultIncludePaths = [
  "AGENTS.md",
  "README.md",
  "package.json",
  "package-lock.json",
  "harness.toml",
  ".nvmrc",
  ".R-version",
  "rust-toolchain.toml",
  "index.html",
  "vite.config.ts",
  "tsconfig.json",
  "src",
  "src-tauri",
  "crates",
  "scripts",
  "schemas",
  "mappings",
  "templates",
  "shinylive-src",
  "data-packs",
  "docs",
];

const excludedSegments = new Set([
  ".git",
  "node_modules",
  "target",
  "dist",
  "apps",
  "reports",
  "release",
  ".vite",
  ".DS_Store",
]);

const parseOptions = (values) => {
  const options = { _: [] };
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!value.startsWith("--")) {
      options._.push(value);
      continue;
    }
    const key = value.slice(2);
    const next = values[index + 1];
    if (!next || next.startsWith("--")) {
      options[key] = true;
    } else {
      options[key] = next;
      index += 1;
    }
  }
  return options;
};

const repoRelative = (targetPath) => {
  const resolved = path.resolve(targetPath);
  const root = path.resolve(rootDir);
  return resolved.startsWith(root) ? toPosix(path.relative(rootDir, resolved)) : resolved;
};

const shouldInclude = (relativePath) => {
  const segments = toPosix(relativePath).split("/");
  return !segments.some((segment) => excludedSegments.has(segment));
};

const copySelected = async (includePaths, starterRoot) => {
  for (const includePath of includePaths) {
    if (!shouldInclude(includePath)) {
      continue;
    }
    const source = path.join(rootDir, includePath);
    if (!(await exists(source))) {
      continue;
    }
    const destination = path.join(starterRoot, includePath);
    await mkdir(path.dirname(destination), { recursive: true });
    await cp(source, destination, {
      recursive: true,
      filter: (sourcePath) => {
        const relative = path.relative(rootDir, sourcePath);
        return shouldInclude(relative);
      },
    });
  }
};

const writeTemplateReadme = async (starterRoot, config) => {
  const lines = [
    `# ${config.project.bundleName} Starter Template`,
    "",
    "This starter was generated by `tauri-shinylive-harness package-template`.",
    "",
    "## Quickstart",
    "",
    "```sh",
    "npm install",
    "npm run validate:config",
    "npm run validate:data",
    "npm run export:reports",
    "npm run export:report-pdfs",
    "npm run clinical:cdisc-preflight",
    "npm run verify",
    "```",
    "",
    "## Boundaries",
    "",
    "- Keep `harness.toml` as the source of truth.",
    "- Edit Shinylive sources under `shinylive-src/*` and reusable synthetic data under `data-packs/*`.",
    "- Generated outputs under `apps/`, `dist/`, `reports/`, and `release/` are intentionally excluded from this starter.",
    "- Do not add real patient data.",
    "- Code signing, notarization, Windows signing, GitHub Release publication, and npm publish require organization credentials.",
    "",
  ];
  await writeFile(path.join(starterRoot, "STARTER_TEMPLATE.md"), lines.join("\n"));
};

const makeZipIfRequested = async ({ starterRoot, destination }) => {
  if (process.platform === "win32") {
    await runCommand("powershell", [
      "-NoProfile",
      "-Command",
      "& { param([string]$Source, [string]$Destination) Compress-Archive -LiteralPath $Source -DestinationPath $Destination -Force }",
      starterRoot,
      destination,
    ]);
    return;
  }
  await rm(destination, { force: true });
  await runCommand("zip", ["-r", "-X", destination, path.basename(starterRoot)], {
    cwd: path.dirname(starterRoot),
  });
};

export const createTemplatePackage = async ({
  outputRoot = defaultOutputRoot,
  includePaths = defaultIncludePaths,
  reportPath = defaultReportPath,
  writeReport = true,
  zip = false,
} = {}) => {
  const config = await readConfig();
  const starterName = `${config.distribution.artifactName}-starter`;
  const starterRoot = path.join(outputRoot, starterName);
  await rm(starterRoot, { recursive: true, force: true });
  await mkdir(starterRoot, { recursive: true });
  await copySelected(includePaths, starterRoot);
  await writeTemplateReadme(starterRoot, config);

  const files = (await listFiles(starterRoot)).sort();
  const manifestFiles = [];
  for (const file of files) {
    const fullPath = path.join(starterRoot, file);
    const metadata = await stat(fullPath);
    manifestFiles.push({
      path: toPosix(file),
      size: metadata.size,
      sha256: await sha256File(fullPath),
    });
  }

  let zipArtifact = null;
  if (zip) {
    const zipPath = path.join(outputRoot, `${starterName}.zip`);
    await makeZipIfRequested({ starterRoot, destination: zipPath });
    zipArtifact = {
      path: repoRelative(zipPath),
      size: (await stat(zipPath)).size,
      sha256: await sha256File(zipPath),
    };
  }

  const packageJsonPath = path.join(starterRoot, "package.json");
  const packageJson = (await exists(packageJsonPath)) ? JSON.parse(await readFile(packageJsonPath, "utf8")) : {};
  const result = {
    schemaVersion: 1,
    ok: true,
    generatedAt: new Date().toISOString(),
    sourceProject: config.project,
    output: repoRelative(starterRoot),
    excludedGeneratedOutputs: ["apps", "dist", "reports", "release"],
    npmPackage: {
      name: packageJson.name ?? "tauri-shinylive-harness",
      version: packageJson.version ?? config.project.version,
      private: Boolean(packageJson.private),
      bin: packageJson.bin ? Object.keys(packageJson.bin)[0] : "tauri-shinylive-harness",
      publishReady: false,
      note: "The starter is package-shaped, but npm publish requires an explicit package policy and credentials.",
    },
    summary: {
      includedFileCount: manifestFiles.length,
      zipCreated: Boolean(zipArtifact),
    },
    files: manifestFiles,
    zipArtifact,
  };

  if (writeReport) {
    await writeJson(reportPath, result);
    await appendAudit("package-template", "ok", {
      output: result.output,
      files: manifestFiles.length,
      zipCreated: Boolean(zipArtifact),
    });
  }

  return result;
};

const runCli = async () => {
  const options = parseOptions(process.argv.slice(2));
  const result = await createTemplatePackage({
    outputRoot: options.output ? path.resolve(options.output) : defaultOutputRoot,
    reportPath: options.report ? path.resolve(options.report) : defaultReportPath,
    zip: Boolean(options.zip),
  });
  console.log(
    JSON.stringify(
      {
        ok: result.ok,
        output: result.output,
        report: repoRelative(options.report ? path.resolve(options.report) : defaultReportPath),
        files: result.summary.includedFileCount,
        zip: result.zipArtifact?.path ?? null,
      },
      null,
      2,
    ),
  );
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
